### ISSUE TITLE
How does the bird know if it's clicked?

### ISSUE THREAD

**Issue by rduke1982** [britzl/throwacrow#1]
https://github.com/britzl/throwacrow/blob/20282da9819e0eda2d906b865d74b3253818e520/main/throwacrow.script#L81

Was looking through this for a project and I noticed that there's no obvious way (for me) to tell if the bird is being clicked on.

I see a collision object with a group set for "cursor", but nothing else. Is there a default "cursor" collision for clicks? If so (will test it next), that's new to me. Otherwise, how does the know if the player is clicking on the bird vs. the screen?

**Comment by britzl** [comment]
That "cursor" mask is unused. The `throwacrow.script` checks distance from the click to the game object and if it is less than 50 pixels in distance it is considered a click on the bird.

https://github.com/britzl/throwacrow/blob/master/main/throwacrow.script#L91
